decide/urls.py
from django.contrib import admin
from django.urls import path, include


from . import views

urlpatterns = [
    path("auth/", include("allauth.urls")),
    path("", views.homepage, name="home"),
    path("ideas/", include("ideas.urls")),
    path("workspaces/", include("workspaces.urls")),
    path("admin/", admin.site.urls),
]

ideas/urls.py
from django.urls import path
from ideas import views

app_name = "ideas"
urlpatterns = [
    path("api/", views.IdeaViewSet.as_view({"get": "list", "post": "create"})),
    path("formula/", views.FormulaViewSet.as_view({"get": "list", "post": "create"})),
    path(
        "api/<int:pk>/",
        views.IdeaViewSet.as_view(
            {"get": "retrieve", "put": "update", "delete": "destroy"}
        ),
    ),
    path(
        "formula/<int:pk>/",
        views.FormulaViewSet.as_view(
            {"get": "retrieve", "put": "update", "delete": "destroy"}
        ),
    ),
    path("create/", views.create_idea, name="create"),
    path("", views.list_ideas, name="list"),
    path("edit/<int:id>", views.edit_ideas, name="edit"),
]

workspaces/urls.py
from django.urls import path
from workspaces import views

app_name = "workspaces"
urlpatterns = [
    path(
        "",
        views.ListWorkspaces.as_view(),
        name="list",
    ),
    path("create/", views.create_workspace, name="create"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="h-full">

<head>
    <title>Decide</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <script src="{% static 'main.js' %}"></script>
</head>

<body class="h-full">
    <wrapper class="flex flex-row h-full">
        <nav class="flex flex-col px-10 bg-zinc-100">
            <div class="workspaceDisplay">{{user.workspace.name}}</div>
            <a class="navItem" href="{% url 'home' %}">Home</a>
            <a class="navItem" href="{% url 'ideas:list' %}">Ideas</a>
            <a class="navItem" href="">Boards</a>
            <a class="navItem" href="{% url 'workspaces:list' %}">Settings</a>
            <a class="navItem" href="{% url 'account_logout' %}">Logout</a>
        </nav>
        <div class="flex-1">
            {% block content%}
            {% endblock %}
        </div>
    </wrapper>

</body>

</html>

templates/create_workspace.html
{% extends "base.html" %}
{% block content %}
    <h1>Name you workspace</h1>
    <form method="POST">
        {% csrf_token %}
        {{ ws_form.as_p }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block content%}
Home
{% endblock %}

templates/ideas_create.html
{% extends "base.html" %}
{% block content %}
{% include "components/pageHeader.html" %}
    <h1>Create idea</h1>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

templates/ideas_list.html
{% extends "base.html" %}
{% block content %}

<div class="p-4 sm:px-6 lg:px-8">
    <div class="sm:flex sm:items-center">
        <div class="flex flex-row justify-between items-center w-full">
            <h1 class="text-lg font-black leading-6 text-gray-900">Ideas</h1>
            <div id="actions">
                <a class="rounded px-3 py-2 bg-blue-700 hover:bg-blue-100 hover:text-black text-white" type="button" href="{% url 'ideas:create' %}">
                Create idea </a>
                <a class="rounded mx-2 px-3 py-2 bg-blue-700 hover:bg-blue-100 hover:text-black text-white" type="button" href="#">Import from Linear</a>
                <a class="rounded px-3 py-2 bg-white border border-slate-400 hover:bg-blue-100 hover:text-black" type="button"
                href="#">Manage formula</a></div>
            </div> 
            </div>

    </div>
    <div class="mt-8 flow-root">
        <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
                <div class="relative">
                    <!-- Selected row actions, only show when rows are selected. -->
                    <!-- <div class="absolute top-0 left-14 flex h-12 items-center space-x-3 bg-white sm:left-12"> -->
                    <!--   <button type="button" class="inline-flex items-center rounded bg-white px-2 py-1 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-30 disabled:hover:bg-white">Bulk edit</button> -->
                    <!--   <button type="button" class="inline-flex items-center rounded bg-white px-2 py-1 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-30 disabled:hover:bg-white">Delete all</button> -->
                    <!-- </div> -->
                     <table class="min-w-full table-fixed divide-y divide-gray-300">
                        <thead>
                            <tr>
                                <th scope="col" class="relative px-7 sm:w-12 sm:px-6">
                                    <input type="checkbox"
                                        class="absolute left-4 top-1/2 -mt-2 h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-600">
                                </th>
                                <th scope="col"
                                    class="min-w-[12rem] py-3.5 pr-3 text-left text-sm font-semibold text-gray-900">Name
                                </th>
                                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Description
                                </th>
                                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Votes
                                </th>
                                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Priority
                                </th>
                                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Calculated
                                                                </th>
                                <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-3">
                                    <span class="sr-only">Edit</span>
                                </th>
                            </tr>
                        </thead>
                        <tbody class="divide-y divide-gray-200 bg-white">
                            {% for idea in ideas %}
                            <!-- Selected: "bg-gray-50" -->
                            <tr class="hover:bg-slate-100 hover:cursor-pointer">
                                <td class="relative px-7 sm:w-12 sm:px-6">
                                    <!-- Selected row marker, only show when row is selected. -->
                                    <!-- <div class="absolute inset-y-0 left-0 w-0.5 bg-indigo-600"></div> -->

                                    <input type="checkbox"
                                        class="absolute left-4 top-1/2 -mt-2 h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-600">
                                </td>
                                <!-- Selected: "text-indigo-600", Not Selected: "text-gray-900" -->
                                <td class="whitespace-nowrap py-4 pr-3 text-sm font-medium text-gray-900">{{idea.name}}
                                </td>
                                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{idea.content}}</td>
                                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{idea.votes_count}}
                                </td>
                                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{idea.priority}}</td>
                                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{idea.calculated}}</td>
                                <td class="whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-3">
                                    <a href="{% url 'ideas:edit' id=idea.id %}" class="text-indigo-600 hover:text-indigo-900">Edit</a>
                                </td>
                            </tr>
                            {% endfor %}
                            <!-- More people... -->
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}